spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://119.3.133.63:53306/eshop?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC}
    username: ${DB_USER:root}
    password: ${DB_PASS:Today_is_begain}
mybatis:
  configuration:
    map-underscore-to-camel-case: true

# 自定义参数
comment:
  picture:
    upload:
      type: ${UPLOAD_TYPE:relative}
      dir: ${UPLOAD_DIR:/}
      ak: ${UPLOAD_AK:}
      sk: ${UPLOAD_SK:}
      point: ${UPLOAD_URL:}